"""SQLAlchemy database models for ExpiryAware."""
from datetime import datetime, timezone
from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from .database import Base


def utc_now():
    """Return timezone-aware UTC timestamp stripped of tzinfo for clean SQLite datetime storage."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class InventoryBatch(Base):
    """Inventory batch model representing medicine stock at a specific location."""
    __tablename__ = "inventory"

    batch_id = Column(String, primary_key=True, index=True)
    medicine_code = Column(String, index=True, nullable=False)
    medicine_name = Column(String, nullable=False)
    medicine_category = Column(String, index=True, nullable=False)
    source_location = Column(String, index=True, nullable=False)
    quantity = Column(Float, nullable=False)
    unit_value = Column(Float, nullable=False)
    expiry_date = Column(String, nullable=False)  # ISO YYYY-MM-DD
    avg_daily_demand = Column(Float, nullable=True)  # Daily consumption at source
    destination_location = Column(String, nullable=True)
    destination_daily_demand = Column(Float, nullable=True)  # Daily consumption at candidate destination
    transfer_distance_km = Column(Float, nullable=True)
    temperature_sensitive = Column(Boolean, default=False)
    data_quality_score = Column(Float, default=100.0)
    created_at = Column(DateTime, default=utc_now)

    # Relationships
    recommendations = relationship("Recommendation", back_populates="batch", cascade="all, delete-orphan")


class Recommendation(Base):
    """Redistribution recommendation model generated by the explainable engine."""
    __tablename__ = "recommendations"

    recommendation_id = Column(String, primary_key=True, index=True)
    batch_id = Column(String, ForeignKey("inventory.batch_id"), nullable=False, index=True)
    medicine_code = Column(String, index=True, nullable=False)
    medicine_name = Column(String, nullable=False)
    source_location = Column(String, index=True, nullable=False)
    destination_location = Column(String, index=True, nullable=False)
    current_quantity = Column(Float, nullable=False)
    recommended_transfer_quantity = Column(Float, nullable=False)
    days_to_expiry = Column(Integer, nullable=False)
    stock_value = Column(Float, nullable=False)
    risk_score = Column(Float, nullable=False)
    expiry_score = Column(Float, default=0.0)
    surplus_score = Column(Float, default=0.0)
    demand_score = Column(Float, default=0.0)
    location_score = Column(Float, default=0.0)
    data_quality_score = Column(Float, default=100.0)
    priority = Column(String, index=True, nullable=False)  # HIGH PRIORITY, MEDIUM PRIORITY, LOW PRIORITY, NO ACTION
    confidence = Column(Float, nullable=False)
    confidence_level = Column(String, nullable=False)  # HIGH CONFIDENCE, MEDIUM CONFIDENCE, LOW CONFIDENCE
    status = Column(String, index=True, default="PENDING")  # PENDING, APPROVED, REJECTED, OVERRIDDEN, BLOCKED, WARNING
    explanation = Column(Text, nullable=False)
    evidence_json = Column(Text, nullable=False)  # Serialized evidence and rule triggers
    created_at = Column(DateTime, default=utc_now)
    updated_at = Column(DateTime, default=utc_now, onupdate=utc_now)

    batch = relationship("InventoryBatch", back_populates="recommendations")


class AuditLog(Base):
    """Immutable audit log for all human decision events."""
    __tablename__ = "audit_log"

    audit_id = Column(String, primary_key=True, index=True)
    recommendation_id = Column(String, index=True, nullable=False)
    batch_id = Column(String, nullable=True)
    action = Column(String, index=True, nullable=False)  # APPROVED, REJECTED, OVERRIDDEN
    user_role = Column(String, nullable=False)  # Pharmacist, Inventory Manager, Clinic Administrator, Clinical Lead
    reason = Column(String, nullable=False)
    notes = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=utc_now, index=True)
